### ISSUE TITLE
override template

### ISSUE THREAD

**Issue by h1alexbel** [Blamer-io/bot#1]

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#4](https://github.com/Blamer-io/bot/issues/4) is still not solved.

**Comment by 0pdd** [comment]
@h1alexbel 2 puzzles [#10](https://github.com/Blamer-io/bot/issues/10), [#9](https://github.com/Blamer-io/bot/issues/9) are still not solved; solved: [#4](https://github.com/Blamer-io/bot/issues/4).

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#10](https://github.com/Blamer-io/bot/issues/10) is still not solved; solved: [#4](https://github.com/Blamer-io/bot/issues/4), [#9](https://github.com/Blamer-io/bot/issues/9).
