### ISSUE TITLE
bot token is stored insecurily

### ISSUE THREAD

**Issue by h1alexbel** [Blamer-io/bot#14]
https://github.com/Blamer-io/bot/blob/b2ca455ae2dbaa6fb363bb8c91eab0ebb95e998a/pom.xml#L109-L110

**Comment by l3r8yJ** [comment]
@h1alexbel it's just a dummy bot's creds, we don't care about that

**Comment by l3r8yJ** [comment]
wdyt

**Comment by h1alexbel** [comment]
@l3r8yJ it's for testing purposes?

**Comment by l3r8yJ** [comment]
@h1alexbel yes it is

**Comment by h1alexbel** [comment]
@l3r8yJ nice, resolved
