### ISSUE TITLE
indentation

### ISSUE THREAD

**Issue by h1alexbel** [Blamer-io/bot#15]
@l3r8yJ we need to decide, what indentation we are using in the project: 2/4?

**Comment by l3r8yJ** [comment]
@h1alexbel i'm usually prefer 4, wdyt?

**Comment by h1alexbel** [comment]
checkstyle suggests me 2, and I'm usually working with 2 indentation

**Comment by l3r8yJ** [comment]
yeah, go ahead with 2

**Comment by h1alexbel** [comment]
ok, resolved
