### ISSUE TITLE
message properties

### ISSUE THREAD

**Issue by h1alexbel** [Blamer-io/bot#16]
instead writing poems in the source code as plain strings we should refer to the `.properties` file with key to actual text.

like in the https://github.com/self-xdsd/self-core/blob/8969d46abdeaf4ea50c0c805ae0822ccccd9a219/self-core-impl/src/test/resources/responses_en.properties#L6

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#22](https://github.com/Blamer-io/bot/issues/22) is still not solved; solved: [#19](https://github.com/Blamer-io/bot/issues/19).

**Comment by h1alexbel** [comment]
Solution is implemented, so it can be closed

**Comment by 0pdd** [comment]
@h1alexbel all 2 puzzles are solved here: [#19](https://github.com/Blamer-io/bot/issues/19), [#22](https://github.com/Blamer-io/bot/issues/22).
