### ISSUE TITLE
checkstyle-suppressions.xml:32: move message text to...

### ISSUE THREAD

**Issue by 0pdd** [Blamer-io/bot#19]
The puzzle `16-6e4c5756` from #16 has to be resolved: 

https://github.com/Blamer-io/bot/blob/b37ea9254f8c7bd7f6bb35bc4668d82c4bd45243/checkstyle-suppressions.xml#L32-L32

The puzzle was created by @h1alexbel on 27-Apr-23. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by l3r8yJ** [comment]
i'm on it

**Comment by 0pdd** [comment]
@0pdd the puzzle [#22](https://github.com/Blamer-io/bot/issues/22) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#22](https://github.com/Blamer-io/bot/issues/22) is solved here.
