### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by l3r8yJ** [Blamer-io/bot#26]
add `Dockerfile` and GHA to push latest container

**Comment by l3r8yJ** [comment]
@h1alexbel added `docker.hub` creds in repo secrets for GHA

**Comment by h1alexbel** [comment]
@l3r8yJ nice, and what are the keys for them?

**Comment by l3r8yJ** [comment]
@h1alexbel `DOCKERHUB_USERNAME` and `DOCKERHUB_PASSWORD`
