### ISSUE TITLE
Fake Bot Configuration

### ISSUE THREAD

**Issue by h1alexbel** [Blamer-io/bot#27]
We can implement fake objects for bot testing.
Or specify the test credentials(token, name) in the Prod Bot Config

https://github.com/yegor256/wring/blob/6883e6e115a036384af638355aa02adc1b9a5414/src/main/java/io/wring/dynamo/Dynamo.java#L74

**Comment by l3r8yJ** [comment]
@h1alexbel test creds are already provided in the plugin or did I misunderstand?

**Comment by h1alexbel** [comment]
@l3r8yJ sure, sorry for confusion
