### ISSUE TITLE
docker.io registry is not created

### ISSUE THREAD

**Issue by h1alexbel** [Blamer-io/bot#29]
@l3r8yJ can you create a docker.io repository for `bot` app?

**Comment by l3r8yJ** [comment]
@h1alexbel give me 5 mins

**Comment by l3r8yJ** [comment]
@h1alexbel [see](https://hub.docker.com/repository/docker/l3r8y/blamer-bot/general)

**Comment by h1alexbel** [comment]
@l3r8yJ nice, thanks
