### ISSUE TITLE
Docker fails

### ISSUE THREAD

**Issue by l3r8yJ** [Blamer-io/bot#32]
seems like gha `docker` fails

**Comment by h1alexbel** [comment]
Run true is missing

**Comment by h1alexbel** [comment]
I will fix it

**Comment by l3r8yJ** [comment]
@h1alexbel I think this is where you can merge directly, as long as it doesn't work

**Comment by h1alexbel** [comment]
@l3r8yJ looks like it works!

**Comment by l3r8yJ** [comment]
@h1alexbel see, thanks!
