### ISSUE TITLE
Rsocket auth

### ISSUE THREAD

**Issue by l3r8yJ** [Blamer-io/bot#41]

**Comment by 0pdd** [comment]
@l3r8yJ 5 puzzles [#43](https://github.com/Blamer-io/bot/issues/43), [#44](https://github.com/Blamer-io/bot/issues/44), [#45](https://github.com/Blamer-io/bot/issues/45), [#46](https://github.com/Blamer-io/bot/issues/46), [#47](https://github.com/Blamer-io/bot/issues/47) are still not solved.
