### ISSUE TITLE
move logo to `blamer.io` website

### ISSUE THREAD

**Issue by h1alexbel** [Blamer-io/bot#48]

**Comment by h1alexbel** [comment]
@l3r8yJ WDYT?

**Comment by l3r8yJ** [comment]
@h1alexbel can you specify details?

**Comment by l3r8yJ** [comment]
![blamer-notifications](https://user-images.githubusercontent.com/46355873/235347536-245c60f5-1c49-4c09-ac73-4a6f7a7a4bc7.svg)
![blamer-hub](https://user-images.githubusercontent.com/46355873/235347538-f70f782a-e23a-4dbe-8398-85ff4d015a04.svg)


@h1alexbel I think I understand you, you can also put these logos on the website, wdyt?

**Comment by h1alexbel** [comment]
@l3r8yJ I mean move `.svg`s from this repo to the blamer.io website

**Comment by l3r8yJ** [comment]
@h1alexbel ah, sure good suggestion
