### ISSUE TITLE
Find a Spring-compatible checkstyle configuration

### ISSUE THREAD

**Issue by l3r8yJ** [Blamer-io/bot#5]
We need to find some existing configuration for checkstyle, because setting it up manually might piss off the person who tries to do it. Spring framework is not the best solution for clean code, but we should try to keep it as clean as possible

**Comment by h1alexbel** [comment]
@l3r8yJ I'm work on it

**Comment by 0pdd** [comment]
@l3r8yJ the puzzle [#18](https://github.com/Blamer-io/bot/issues/18) is still not solved.

**Comment by 0pdd** [comment]
@l3r8yJ the only puzzle [#18](https://github.com/Blamer-io/bot/issues/18) is solved here.
