### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by l3r8yJ** [Blamer-io/bot#50]
https://github.com/Blamer-io/bot/blob/56de4f43400158fff754b01c8baf9ea565a50ed2/Dockerfile#L31-L32

@h1alexbel do we really need this time zone, I'm talking about the time zone in general?

**Comment by h1alexbel** [comment]
@l3r8yJ by default can be bugs with this. Like logging time and so, on. So, it good to stay with some.
If needed, we can change it

**Comment by l3r8yJ** [comment]
@h1alexbel got you, I think we can stay as is
