### ISSUE TITLE
sequence diagrams for all flows

### ISSUE THREAD

**Issue by h1alexbel** [Blamer-io/bot#66]

**Comment by zoeself** [comment]
@h1alexbel this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2023-09-09T06:41:23.213042``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@h1alexbel please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by h1alexbel** [comment]
@l3r8yJ I think after closing this one, we can remove diagrams from hub, all diagrams will be here

WDYT?

**Comment by zoeself** [comment]
@h1alexbel Don't forget to close this ticket before the deadline (2023-09-09T06:41:23). You are past the first half of the allowed period.

**Comment by h1alexbel** [comment]
@l3r8yJ reminder, check #72
