### ISSUE TITLE
do we need to schedule job for receiving notifications stream?

### ISSUE THREAD

**Issue by h1alexbel** [Blamer-io/bot#67]

**Comment by zoeself** [comment]
@h1alexbel this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2023-09-09T19:00:36.287344``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@h1alexbel please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by h1alexbel** [comment]
![sequence-Notifications_Read_Flow](https://github.com/Blamer-io/bot/assets/83453843/c596a2fc-ff69-40c8-9066-a4cfdd5e4869)


@l3r8yJ here is the diagram, do we need to schedule this flow based on user toggled token (every 5 minutes) OR user will toggle the token and blamer will watch the notifications and supply them on demand

What do you think?

**Comment by l3r8yJ** [comment]
@h1alexbel i think flow should be like this, wdyt?

user registers token once --> token validation --> notification service long polls github api --> notifications go to services

**Comment by l3r8yJ** [comment]
This is why I prefer a reactive stack, notifications should be similar to a stream

Flux become very useful here

**Comment by h1alexbel** [comment]
@l3r8yJ got it, I will redesign my sketches

**Comment by h1alexbel** [comment]
@l3r8yJ what are the stuff we save to database?

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Comment by l3r8yJ** [comment]
@h1alexbel i suppose just `chatId` and crypted `token`, wdyt?
