### ISSUE TITLE
add token success flow

### ISSUE THREAD

**Issue by h1alexbel** [Blamer-io/bot#68]
![add-token-Add_Token_Success_Flow](https://github.com/Blamer-io/bot/assets/83453843/5ce61694-d151-4263-a088-ba4856d4435f)

**Comment by zoeself** [comment]
@h1alexbel thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by h1alexbel** [comment]
@zoeself deregister

**Comment by zoeself** [comment]
> @zoeself deregister

@h1alexbel ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by h1alexbel** [comment]
@l3r8yJ what do you think?
I think it's will be better to validate all tokens continuously on Auth service

Thus, in case of token expiration Auth service will notify the User that token is expired, and notifications system in read flow will not use that token to poll notifications

**Comment by h1alexbel** [comment]
@l3r8yJ  take a look, please
