### ISSUE TITLE
notifications read flow

### ISSUE THREAD

**Issue by h1alexbel** [Blamer-io/bot#70]
![sequence-Notifications_Read_Flow](https://github.com/Blamer-io/bot/assets/83453843/dcda81c8-d713-4622-80cf-ed89070b3a50)

**Comment by zoeself** [comment]
@h1alexbel please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by h1alexbel** [comment]
@l3r8yJ what do you think?

**Comment by zoeself** [comment]
@h1alexbel Don't forget to close this ticket before the deadline (2023-09-11T06:19:18). You are past the first half of the allowed period.

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
