### ISSUE TITLE
token validation process

### ISSUE THREAD

**Issue by h1alexbel** [Blamer-io/bot#71]
![token-validation-Token_Validation_Process](https://github.com/Blamer-io/bot/assets/83453843/87c232ff-0657-4bb3-a03e-05103ee4d3df)

**Comment by zoeself** [comment]
@h1alexbel thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by h1alexbel** [comment]
@zoeself deregiste

**Comment by zoeself** [comment]
> @zoeself deregiste 

@h1alexbel didn't understand that, sorry.

**Comment by h1alexbel** [comment]
@zoeself deregister

**Comment by zoeself** [comment]
> @zoeself deregister

@h1alexbel ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by h1alexbel** [comment]
@l3r8yJ  take a look, please
